LearningEnabled: true
World:
  WorldWidth: 1200
  WorldHeight: 800
MutationRate: 0.03
SimulationSpeed: 1
Population:
  InitialCreatureCount: 20
  InitialParasiteCount: 20
  InitialPlantClusters: 20
  MaxPlantsPerCluster: 15
  GlobalMaxPlantCount: 500
  InitialPlantClusterRadius: 10.0
Creature:
  MovementEnergyCostFactor: 0.005
  ReproductionEnergyThreshold: 70
  DragCoefficient: 0.1
  AngularDragCoefficient: 0.0
  ReproductionProbability: 0.01
Plant:
  EnergyGain: 12.0
  ReproductionProbability: 0.02
  SeedMaturityThreshold: 5.0
  SeedDispersalProbability: 0.003
  SeedDispersalRadius: 50.0
Physics:
  LinearForceScaling: 30.0
  AngularForceScaling: 1000.0
  LinearDragCoefficient: 0.5
  TorqueDragCoefficient: 50
  JetCooldown: 0.2
Render:
  PlantRenderRadius: 2